### ISSUE TITLE
Correlation metrics are not available

### ISSUE THREAD

**Issue by hh1985** [caporaso-lab/tax-credit#148]
Hi I noticed that the metrics Pearson r and Spearman r were removed from the code.  Are they too poor to use for 16s rRNA data?  I am curious to know the reason.  Thanks a lot! 

-hh1985

**Comment by nbokulich** [comment]
Hi @hh1985, thanks for asking! I removed these metrics because they were not particularly useful and were very prone to disturbance in compositional data. Overall, other quantitative metrics such as F-measure are much more informative.

These should still be somewhere in the version history if they are needed.

**Comment by hh1985** [comment]
Hi @nbokulich , thanks for the information!  If Pearson/Spearman correlation is not recommended, what should I use to evaluate the quantification performance of a method?

**Comment by nbokulich** [comment]
Hi @hh1985 I would recommend the precision/recall/F-measure metrics. Check out the ipython notebooks (any with "evaluation" in the name) to see how to use these on taxonomy classification data in tax-credit.

**Comment by hh1985** [comment]
@nbokulich Thanks a lot!
